version: '3'
services:
 web:
  build:
   context: .
   dockerfile: Dockerfile.dev
  ports:
   - "3000:3000"
  stdin_open: true
  environment:
   - CHOKIDAR_USEPOLLING=true
 tests:
  build:
   context: .
   dockerfile: Dockerfile.dev
  command: ["npm", "run", "test"]
  stdin_open: true
  environment:
   - CHOKIDAR_USEPOLLING=true